GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.0
  visualize_potential: false
  publish_potential : true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3
  orientation_mode: 0
  orientation_window_size: 1
  outline_map: true
