DWAPlannerROS:
#ROBOT_CONFIGURATION_PARAMETER
  max_vel_x: 0.25 #0.2
  min_vel_x: 0.2 #0.0
  max_vel_y: 0.0 #0.1
  min_vel_y: 0.0 #-0.1
  max_vel_trans:  0.25 #0.2
  min_vel_trans:  0.2 #0.0
  max_vel_theta: 1.0 #0.2
  min_vel_theta: 0.3 #0.0
  acc_lim_x: 0.05
  acc_lim_y: 0.05
  acc_lim_theta: 0.05
  #acc_lim_trans: 3.2
#
  prune_plan: true

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05

  trans_stopped_vel: 0.05
  theta_stopped_vel: 0.1

  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  vx_samples: 3
  vy_samples: 10
  vth_samples: 20
  controller_frequency: 20

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  twirling_scale: 0.0
  stop_time_buffer: 0.2

  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2
  forward_point_distance: 0.325

  scaling_speed: 0.45
  max_scaling_factor: 0.2
  
