<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	
	    <material name="black">
		<color rgba="0.0 0.0 0.0 1.0"/>
	    </material>

	    <material name="blue">
		<color rgba="0.0 0.0 0.8 1.0"/>
	    </material>

	    <material name="green">
		<color rgba="0.0 0.8 0.0 1.0"/>
	    </material>

	    <material name="grey">
		<color rgba="0.2 0.2 0.2 1.0"/>
	    </material>

	    <material name="orange">
		<color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
	    </material>

	    <material name="brown">
		<color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
	    </material>

	    <material name="red">
		<color rgba="0.8 0.0 0.0 1.0"/>
	    </material>

	    <material name="white">
		<color rgba="1.0 1.0 1.0 1.0"/>
	    </material>

	    <material name="stainless">
		<color rgba="${224/255} ${223/255} ${219/255} 1.0"/>
	    </material>

	    <material name="aluminium">
		<color rgba="${132/255} ${135/255} ${137/255} 1.0"/>
	    </material>
	    
	    
	  

	    <xacro:property name="body_length" value="0.31"/>
	    <xacro:property name="body_width" value="0.4"/>
	    <xacro:property name="body_height" value="0.2"/>
	    <xacro:property name="body_mass" value="12"/>
	    
	    <xacro:property name="base_caster_length" value="0.02"/>
	    <xacro:property name="base_caster_width" value="0.02"/>
	    <xacro:property name="base_caster_height" value="0.37"/>
	    
	    <xacro:property name="above_base_caster_length" value="0.12"/>
	    <xacro:property name="above_base_caster_width" value="0.4"/>
	    <xacro:property name="above_base_caster_height" value="0.0075"/>
	    
	    <xacro:property name="wheel_radius" value="0.072"/>
	    <xacro:property name="wheel_width" value="0.04"/>
	    <xacro:property name="wheel_mass" value="0.4"/>
	    <xacro:property name="wheel_separation" value="0.46"/>
	    <xacro:property name="PI" value="3.1415926535897931"/>
	    
	    <xacro:macro name="cylinder_inertia" params="m r h">
		<inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
		         iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
		         izz="${m*r*r/2}"/> 
	    </xacro:macro>

	    <xacro:macro name="box_inertia" params="m l w h">
		<inertia ixx="${m*(h*h+l*l)/12}" ixy = "0" ixz = "0"
		         iyy="${m*(w*w+h*h)/12}" iyz = "0"
		         izz="${m*(w*w+l*l)/12}" /> 
	    </xacro:macro>
    	
    	<link name="base_footprint">
    		<origin xyz="0.0 0.0 0.0"/>
       
    	</link>
    	       
       <joint name="base_footprint_joint" type="fixed">
       	<origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
        	<parent link="base_footprint"/>
        	<child link="base_link"/>
        	
    	</joint>
        	
       <link name="base_link">
       	<origin xyz="0.0 0.0 0.0"/>
       
       </link>



       
    <!-- CHASSIS_LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.16 0.0 0.0"/>
    </joint>

    <link name="chassis">
        <inertial>
            <origin xyz="0.2055 0.0 0.07" rpy="0.0 0.0 0.0"/>
            <mass value="${body_mass}"/>
            <xacro:box_inertia m="${body_mass}" l="${body_length}" w="${body_width}" h="${body_height}"/>
        </inertial>
        <visual>
            <origin xyz="0.2055 0.0 0.07" rpy="0.0 0.0 0.0"/>
            <geometry>
                 <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="aluminium"/>
        </visual>
        <collision>
            <origin xyz="0.2055 0.0 0.07" rpy="0.0 0.0 0.0"/>
            <geometry>
                 <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
    </link>
       
       

<!--right wheel-->
       
       <link name="right_wheel">
         	<visual>
           		<geometry>
             			<cylinder radius="${wheel_radius}" length="${wheel_width}"/>
           		</geometry>
           		<material name="blue"/>
         	</visual>
         	<collision>
           		<geometry>
             			<cylinder radius="${wheel_radius}" length="${wheel_width}"/>
           		</geometry>
         	</collision>
       	<inertial>
            		<mass value="${wheel_mass}"/>
            		<xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        	</inertial>
       </link>
       <joint name="right_wheel_joint" type="continuous">
         	<parent link="base_link"/>
         	<child link="right_wheel"/>
         	<origin xyz="-0.03 -0.23 0.0" rpy="${PI/2} 0 0"/>
         	<axis xyz="0 0 -1"/>
       </joint>

	
<!--left wheel-->

	<link name="left_wheel">
         	<visual>
           		<geometry>
             			<cylinder radius="${wheel_radius}" length="${wheel_width}"/>
           		</geometry>
           		<material name="blue"/>
         	</visual>
         	<collision>
           		<geometry>
             			<cylinder radius="${wheel_radius}" length="${wheel_width}"/>
           		</geometry>
         	</collision>
         	<inertial>
            		<mass value="${wheel_mass}"/>
            		<xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        	</inertial>
       </link>  
       <joint name="left_wheel_joint" type="continuous">
       	<parent link="base_link"/>
         	<child link="left_wheel"/>
         	<origin xyz="-0.03 0.23 0.0" rpy="${-PI/2} 0.0 0.0"/>
         	<axis xyz="0 0 1"/>
       </joint>
       
        
       
<!--base caster lidar-->
	<link name = "above_base_caster" >
		<visual> 
			<geometry>
				<box size="${above_base_caster_length} ${above_base_caster_width} ${above_base_caster_height}"/>
			</geometry>
			<material name = "stainless" />
		</visual>
		<collision> 
			<geometry>
				<box size="${above_base_caster_length} ${above_base_caster_width} ${above_base_caster_height}"/>
			</geometry>
		</collision>
		<inertial>
            		<mass value="0.2" />
            		
            		<inertia ixx="0.1" ixy="0.0" ixz="0.0"
                    		iyy="0.1" iyz="0.0"
                    		izz="0.1" />
        	</inertial>
	</link>
	<joint name="above_base_caster_joint" type="fixed">
         	<parent link="base_link"/>
         	<child link="above_base_caster"/>
         	<origin xyz="-0.075 0.0 0.40" rpy="0 0 0"/>
         	
       </joint>
       
	<link name = "right_base_caster" >
		<visual> 
			<geometry>
				<box size="${base_caster_length} ${base_caster_width} ${base_caster_height}"/>
			</geometry>
			<material name = "white" />
		</visual>
		<collision> 
			<geometry>
				<box size="${base_caster_length} ${base_caster_width} ${base_caster_height}"/>
			</geometry>
		</collision>
		<inertial>
            		<mass value="0.2" />
            		
            		<inertia ixx="0.1" ixy="0.0" ixz="0.0"
                    		iyy="0.1" iyz="0.0"
                    		izz="0.1" />
        	</inertial>
	</link>
	<joint name="right_base_caster_joint" type="fixed">
         	<parent link="base_link"/>
         	<child link="right_base_caster"/>
         	<origin xyz="-0.075 0.17 0.22" rpy="0 0 0"/>
         	
       </joint>
       
	<link name = "left_base_caster" >
		<visual> 
			<geometry>
				<box size="${base_caster_length} ${base_caster_width} ${base_caster_height}"/>
			</geometry>
			<material name = "white" />
		</visual>
		<collision> 
			<geometry>
				<box size="${base_caster_length} ${base_caster_width} ${base_caster_height}"/>
			</geometry>
		</collision>
		<inertial>
            		<mass value="0.2" />
            		
            		<inertia ixx="0.1" ixy="0.0" ixz="0.0"
                    		iyy="0.1" iyz="0.0"
                    		izz="0.1" />
        	</inertial>
	</link>
	<joint name="left_base_caster_joint" type="fixed">
         	<parent link="base_link"/>
         	<child link="left_base_caster"/>
         	<origin xyz="-0.075 -0.17 0.22" rpy="0 0 0"/>
         	
       </joint>
       

	
	
<!--caster wheel-->	
	<link name = "caster_wheel" >
		<visual> 
			<geometry>
				<sphere radius = "0.07" />
			</geometry>
			<material name = "orange" />
		</visual>
		<collision> 
			<geometry>
				<sphere radius = "0.072" />
			</geometry>
		</collision>
		<inertial>
            		<mass value="0.1" />
            		
            		<inertia ixx="0.1" ixy="0.0" ixz="0.0"
                    		iyy="0.1" iyz="0.0"
                    		izz="0.1" />
        	</inertial>
	</link>
	
	<joint name = "caster_wheel_joint" type = "fixed" >
		<parent link = "base_link" />
		<child link = "caster_wheel" />
		<origin xyz = "0.13 0 0.0" />
	</joint>
	
       <!-- lidar -->
    <joint name="joint_scan" type="fixed">
        <origin xyz="-0.075 0.0 ${body_height +0.25+ 0.009}" rpy="0.0 0.0 -0.3837777777777778"/>     <!--0.215 = 0.2 + 0.03/2-->
        <parent link="base_link"/>
        <!-- <child link="base_scan"/> -->
        <child link="laser"/>
    </joint>

    <!-- <link name="base_scan"> -->
    <link name="laser">
        <visual>
            <origin xyz="0.01 0.0 -0.04" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.04" length="0.03"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.01 0.0 -0.04" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.04" length="0.03"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.01 0.0 -0.04" rpy="0.0 0.0 0.0"/>
            <mass value="0.114"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
    </link>
    
    <!--Face robot-->
    <joint name="face_joint" type="fixed">
        <parent link="chassis"/>
        <child link="face_link"/>
        <origin xyz="${body_length} 0 ${body_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="face_link">
        <visual>
            <origin xyz="0.05 0.07 0.075" rpy="0 ${PI/2} 0"/>
            <geometry>
                <cylinder radius="0.025" length="0.002"/>
            </geometry>
            <material name="white"/>
        </visual>

        <visual>
            <origin xyz="0.05 -0.07 0.075" rpy="0 ${PI/2} 0"/>
            <geometry>
                <cylinder radius="0.025" length="0.002"/>
            </geometry>
            <material name="white"/>
        </visual>


        <visual>
            <origin xyz="0.05 0.0 0.0" rpy="0 ${1.5} 0"/>
            <geometry>
                <cylinder radius="0.03" length="0.02"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>


    <!-- plugin lidar -->

    
</robot>

